inherit_gem:
  jekyll: .rubocop.yml
AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - vendor/**/*

Metrics/LineLength:
  Exclude:
    - spec/**/*
    - jekyll-compose.gemspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/IndentHeredoc:
  Exclude:
    - spec/**/*
