version: "{build}"
clone_depth: 5
branches:
  only:
    - master

build: off

environment:
  JEKYLL_VERSION: "~> 3.8"
  matrix:
    - RUBY_FOLDER_VER: "26"
      JEKYLL_VERSION : "~> 3.7.4"
    - RUBY_FOLDER_VER: "26"
      JEKYLL_VERSION : ">= 4.0.0"
    - RUBY_FOLDER_VER: "26"
    - RUBY_FOLDER_VER: "24"
    - RUBY_FOLDER_VER: "23"

install:
  - SET PATH=C:\Ruby%RUBY_FOLDER_VER%-x64\bin;%PATH%
  - bundle install --retry 5 --jobs=%NUMBER_OF_PROCESSORS% --clean --path vendor\bundle

test_script:
  - ruby --version
  - gem --version
  - bundler --version
  - bash ./script/test

cache:
  # If one of the files after the right arrow changes, cache will be invalidated
  - 'vendor\bundle -> appveyor.yml,Gemfile,jekyll-compose.gemspec'
