version: "{build}"
clone_depth: 5
branches:
  only:
    - master

build: off

environment:
  matrix:
    - RUBY_FOLDER_VER: "25-x64"
    - RUBY_FOLDER_VER: "25"
    - RUBY_FOLDER_VER: "24"

install:
  - SET PATH=C:\Ruby%RUBY_FOLDER_VER%\bin;%PATH%
  - bundle install --retry 5 --jobs=%NUMBER_OF_PROCESSORS% --clean --path vendor\bundle

test_script:
  - ruby --version
  - gem --version
  - bundler --version
  - bash ./script/cibuild

cache:
  # If one of the files after the right arrow changes, cache will be invalidated
  - 'vendor\bundle -> appveyor.yml,Gemfile,jekyll-compose.gemspec'
